## Formateo

```{r analisis}
# Revisar ls patrones
head(rse_gene$sra.sample_attributes)
```

```{r arreglar_atributos}
## Arreglar los atributos para que no generen problemas  

# Cambiar el número de semanas por young y old 
rse_gene$sra.sample_attributes <- gsub("8 weeks", "young", rse_gene$sra.sample_attributes)
rse_gene$sra.sample_attributes <- gsub("8-12 weeks", "old", rse_gene$sra.sample_attributes)

# Remplazar los espacios en blaco para que no hayan errores
rse_gene$sra.sample_attributes <- gsub("Whole tissue", "whole-tissue", rse_gene$sra.sample_attributes)
rse_gene$sra.sample_attributes <- gsub("Forebrain tissue", "forebrain_tissue  ", rse_gene$sra.sample_attributes)
rse_gene$sra.sample_attributes <- gsub("Visual cortex", "visual_cortex", rse_gene$sra.sample_attributes)

# Ver cómo queda
rse_gene$sra.sample_attributes[1:12]
```


```{r mod_data}
# Pasar los atributos a factores para poder manipularlos
rse_gene$sra_attribute.phenotype <- factor(rse_gene$sra_attribute.cellular_fraction)
rse_gene$sra_attribute.gender <- factor(rse_gene$sra_attribute.gender)
rse_gene$sra_attribute.genotype <- factor(rse_gene$sra_attribute.genotype)
rse_gene$sra_attribute.source_name <- factor(rse_gene$sra_attribute.source_name)
rse_gene$sra_attribute.strain <- factor(rse_gene$sra_attribute.strain)
rse_gene$sra_attribute.age <- factor(rse_gene$sra_attribute.age)

# Generar resumen de las variables de interes
summary(as.data.frame(colData(rse_gene)[,
    grepl("^sra_attribute.[cellular_fraction|gender|genotype|source_name|strain|age]", colnames(colData(rse_gene)))]))
```


```{r seguridad}
# Hacemos un respaldo 
rse_gene_secure <- rse_gene
```
